# Generated by Django 5.1.2 on 2024-12-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app8', '0002_pagevisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
